name: Salvar Aluno
on:
  workflow_dispatch:
    inputs:
      id:
        description: 'ID do Aluno'
        required: true
      dados:
        description: 'Dados JSON do Aluno'
        required: true

jobs:
  salvar:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão pra criar arquivo
    steps:
      - name: Baixar código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}  # <-- 2 espaços a mais aqui
  
      - name: Criar arquivo
        run: |
          mkdir -p sections/ktp/projetotransformacao/projetos/2026
          echo '${{ inputs.dados }}' > sections/ktp/projetotransformacao/projetos/2026/${{ inputs.id }}.json

      - name: Fazer Commit e Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Adicionar aluno ${{ inputs.id }}" || exit 0
          git push
